# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target ’Grocery Store’ do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Grocery Store


pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'IQKeyboardManager'
pod 'JTCalendar', '~> 2.0'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
end
